factor     = '(' expression ')' | variable | constant;
term       = factor [['*'|'/'] term];
(* Implicit multiplication in input seems to pose a problem*)
expression = term [['+'|'-'] expression];
constant   = ['+'|'-'] number;
